// OpenTelemetry instrumentation for Fastapi-realworld-example-app — generated by TelemetryOS.
// SLO contract v1. SLIs covered: Fastapi-realworld-example-app — HTTP Worker Pool Saturation.
// Adapt the snippets below to your service; they are grounded scaffolds.

package telemetry

import "go.opentelemetry.io/otel"

var (
	meter  = otel.Meter("Fastapi-realworld-example-app")
	tracer = otel.Tracer("Fastapi-realworld-example-app")
)

// ── SLI: Fastapi-realworld-example-app — HTTP Worker Pool Saturation (fastapi-realworld-example-app-http-saturation) — complexity: medium ──
// Active-request and pool-size gauges
activeRequests, _ := meter.Int64ObservableGauge("http.server.active_requests")
poolSize, _ := meter.Int64ObservableGauge("http.server.worker_pool.size")

meter.RegisterCallback(func(_ context.Context, o metric.Observer) error {
  o.ObserveInt64(activeRequests, server.ActiveRequests())
  o.ObserveInt64(poolSize, int64(server.MaxWorkers()))
  return nil
}, activeRequests, poolSize)
